### ISSUE TITLE
Use of Prefix 

### ISSUE THREAD

**Issue by Skylaza** [utarwyn/discord-tictactoe#241]
I mean that instead of using slash command there should be a option for using the command just by the bot's prefix that would be really helpful for those which use prefix to run their commands *you already have made this please send me the docs file of that*

**Comment by utarwyn** [comment]
Hello, yes you can switch from slash command to text command if you want.
In order to do that, you have to set the config value "command" to an empty string and config value "textCommand" with prefix that you want.

Here is an example of what you can do (in the wiki): https://github.com/utarwyn/discord-tictactoe/wiki/Usage-examples-with-Node.js#use-text-command-instead-of-slash-command-discordjs-v13

You can also find few explanations in config interfaces:
https://github.com/utarwyn/discord-tictactoe/blob/6cf6ba29c708800f6f56b4bd20dbe9d5fe179062/src/config/CommandConfig.ts#L7-L20
