### ISSUE TITLE
Duel accept issue

### ISSUE THREAD

**Issue by Ajay01028** [utarwyn/discord-tictactoe#242]
Whenever a user accept the duel challenge bot edit that message to "." and doesn't start a game

**Comment by Gorniaky** [comment]
I already got this error too, most likely you are doing this:

```ts
JSON.parse(<ButtonInteraction>.customId);
```
When the customId is "yes" or "no", `JSON.parse` throws an error

The solution I found was to write a function with try/catch

```ts
function JSONparse(customId) {
  try {
    JSON.parse(customId);
  } catch {
    return;
  }
}
```
With that, you won't have any more problems.

**Comment by Gorniaky** [comment]
I already got this error too, most likely you are doing this:

```ts
JSON.parse(<ButtonInteraction>.customId);
```
When the customId is "yes" or "no", `JSON.parse` throws an error

The solution I found was to write a function with try/catch

```ts
function JSONparse(customId) {
  try {
    JSON.parse(customId);
  } catch {
    return;
  }
}
```
With that, you won't have any more problems.

**Comment by utarwyn** [comment]
Hello @Gorniaky, I don't understand where to fix this in the module source code?

**Comment by Gorniaky** [comment]
@utarwyn the problem is not in the module itself, but when we load a customId that is not encoded in JSON and try to decode it with `JSON.parse`, an error occurs, but there is a solution to this problem: if you use numbers to confirm the duel , `"1"` for "yes" and `"0"` for "no", `JSON.parse` has no problem with numbers.
