### ISSUE TITLE
Edit challenge message

### ISSUE THREAD

**Issue by xJohnnyrl** [utarwyn/discord-tictactoe#258]
I wanna edit the challenge message or other messages to add the amount the user wants to bet on it. I've tried a lot of things but I can't seem to get it, is there any way to do this?

**Comment by utarwyn** [comment]
Hello! You can use a custom language file to adapt messages based on your needs.
Check this wiki page to have more info on it: https://github.com/utarwyn/discord-tictactoe/wiki/Choose-your-language#use-a-custom-language-file

**Comment by ElPiroJ** [comment]
Thanks for the response! I have been editing the en.json file, but the problem I'm having is for example I have an option for people to bet a certain amount, I want to include the amount of that bet in the challenge message but I can't find a way to pass that bet number there since it's not a static number.

**Comment by utarwyn** [comment]
Hello! You can now provide messages with dynamic values programmatically :+1:
Please follow examples in #538 and [the wiki page](https://github.com/utarwyn/discord-tictactoe/wiki/Choose-your-language#provide-messages-programmatically) to check how setup this feature!
