### ISSUE TITLE
using buttons

### ISSUE THREAD

**Issue by humblefool13** [utarwyn/discord-tictactoe#51]
hello , since discord.js V13 is out officially and works great , I would like you to use buttons for the game , the AI is wonderful literally not a single human was able to beat the AI , I dont think changing to buttons will be too much work , but if you do that gonna align the package and bots using the package to latest features available and also buttons can be more easy to use and play in .
I mean something like this - https://cdn.discordapp.com/attachments/852679547199422497/875216094309253180/unknown.png
thank you so much!
also in one server the bot can operate one game at a time I would like you to look into that and make it possible for multiple games simultaneously but of course not for same users , i dont know if its just with me or with everyone

**Comment by utarwyn** [comment]
Hello! Thank you for your suggestion, I didn't know about buttons but I will try that to check if this is useful to add it for the bot 👍 
Sorry but I can't see your image.. it says to me **"AccessDenied"**. As v13 is now stable, I will work on it! Check more here: #48 

About your second idea, it seems to be a bug because game should be able to be started in different channels at the same time. Is it ok or you would like to also have different games in the same channel? I can add an option for that.

**Comment by humblefool13** [comment]
![Capture](https://user-images.githubusercontent.com/85033530/129174584-c8a63af6-b20a-4ad4-9a59-aa9bcd3132b9.PNG)
this is what i meant by using buttons for the game 
and also yes i mean it would be nice if multiple games could be possible simultaneously within same channel for different users like one user must not be able to play two games in same channel at same time irrespective of with AI or with other players.
thank you so much!

**Comment by utarwyn** [comment]
Thank you for the little preview! I will work on that very soon.
I have also created a new issue to speak about simultaneous games in channels: #53.

**Comment by niveKKumar** [comment]
Awesome I was just thinking about exactly these things. Is there a discord Server for this (and maybe other future games )? I would also like to contribute :)
